### ISSUE TITLE
geneUsage——ambiguous gene

### ISSUE THREAD

**Issue by yxjreeeee** [immunomind/immunarch#187]
HI,
   
  when I used the geneusage function to display Vgene and found some ambiguous name genes. Then want to deal with by ‘.ambig = ” wei “ ， but there are errors. Is this parameter removed ? So how to deal with ambiguity genes ?

thanks；
LAI

**Comment by tsvvas** [comment]
Hello,

My name is Vasily, I am a developer of the Immunarch package. Thank you for using it!

Sorry for the late response. We decided to deprecate this method, since it quantifies gene usage in manner, which makes little biological sense. You have two options: simply drop ambiguous genes (`.ambig="exc"`), or use all gene names (`.ambig = "inc"`). In practice first approach works just fine, since ambiguous genes are present in a small amount of clonotypes.

I will close this issue now. If you have any more questions, feel free to open new issue.

Best regards,
Vasily Tsvetkov
