### ISSUE TITLE
Error in running in general

### ISSUE THREAD

**Issue by hryu0125** [immunomind/immunarch#192]
## ❓ Questions and Help
We have a set of [listed tutorials available on the website](https://immunarch.com/articles/).

Hi,

I tried to analyze mixcr data. I successfully uploaded data:

== Step 1/3: loading repertoire files... ==

Processing "/Users/hryu/Desktop/Fred Hutch/projects/COVID-19/COVID vaccine/bulkTCR_COVID/31257_11101" ...
  -- [1/8] Parsing "(not shown)" -- mixcr
  -- [2/8] Parsing "(not shown)" -- mixcr
  -- [3/8] Parsing "(not shown)" -- mixcr 
  -- [4/8] Parsing "(not shown)" -- mixcr
  -- [5/8] Parsing "(not shown)" --  0smixcr
  -- [6/8] Parsing "(not shown)" --  0smixcr
  -- [7/8] Parsing "(not shown)" -- mixcr
  -- [8/8] Parsing "(not shown)" -- metadata
                                                                                               0s
== Step 2/3: checking metadata files and merging files... ==

Processing "(not shown)" ...
  -- Everything is OK!

== Step 3/3: processing paired chain data... ==

Done!

And when I tried to analyze my data:

> imm_ov1 <- repOverlap(immdata_mixcr, .method = "public", .verbose = F)
Error in sum(.) : invalid 'type' (list) of argument
> imm_ov2 <- repOverlap(immdata_mixcr, .method = "morisita", .verbose = F)
Error in sum(.) : invalid 'type' (list) of argument

Those dataset were previously analyzed with immunarch without any issues and now it is not working. 
Not sure what's going on..

Thanks!

**Comment by MVolobueva** [comment]
Hi @christoforos-dimitropoulos!

My name is Maria Volobueva, I am the developer of Immunarch.
Thank you for using the package! Could you provide an example of the file you try to load, as we will be able to quickly identify the issues.

**Comment by MVolobueva** [comment]
Hi @hryu0125!

My name is Maria Volobueva, I am the developer of Immunarch.
Thank you for using the package! Could you provide an example of the file you try to load, as we will be able to quickly identify the issues.

**Comment by hryu0125** [comment]
[a-CD3_TRA.txt](https://github.com/immunomind/immunarch/files/7597678/a-CD3_TRA.txt)
Hi @MVolobueva , here is one of the files that I tried to use. Thanks!

**Comment by MVolobueva** [comment]
Hi, @hryu0125!

Thanks again for reaching out. I took a look at your data and I was able to run repOverlap successfully.

When you load your data with repLoad, you get a list with two elements, namely data and meta. The repOverlap function doesn't work with that list, instead it works only with `immdata$data` list that holds the repertoire data. Here is an example of how to work with repOverlap with Immunarch dataset:

```
data(immdata)
imm_ov1 <- immunarch::repOverlap(.data = immdata$data,.method = "public", .verbose = F)
```
To see more details on the proposed example, take a look at Immunarch's data loading tutorial: https://immunarch.com/articles/v2_data.html

The repOverlap function does not work with the file `a-CD3_TRA.txt` you attached above, because this file contains only one repertoire. I have copied your files twice and made a folder with the same 3 repertoires and meta data (see attached file `192.zip`). The repOverlap works perfectly with files organised this way:

```
dt <- repLoad('/home/masha/immunomind/immunarch-test-files-master/192')
imm_ov1 <- immunarch::repOverlap(.data = dt$data,.method = "public", .verbose = F)
vis(imm_ov1)
```

If you have any questions, feel free to open another issue. Happy Thanksgiving!

Best regards,
Maria
