### ISSUE TITLE
Error in generating circos plot 

### ISSUE THREAD

**Issue by dmnoyong** [immunomind/immunarch#264]
## 🐛 Bug
Hi Aleksandr, 

I tried to generate circos plot using the example given on the vignette, either with vis_circos() or vis(data, .plot = "circos") on matrix data from repOverlap(). However, this resulted in an error message.

I believe this could be a bug?

## To Reproduce

data(immdata)
ov <- repOverlap(immdata$data)
vis(ov, .plot = "circos")
OR 
vis_circos(ov)

Error: Since `gap.degree` parameter has length larger than 1, it should have same length
as the number of sectors.

Thanks for your help,
Damian

**Comment by MVolobueva** [comment]
Hello @dmnoyong,

Thank you for contacting us. My name is Maria Samokhina, I am a developer of the Immunarch package. 
I am glad you are using our software and let's hope I can help you out.

Regarding your question, I ran your code and it works correctly.
This is the result of the first part:
```
data(immdata)
ov <- repOverlap(immdata$data)
vis(ov, .plot = "circos")
```

![Image](https://user-images.githubusercontent.com/72346144/180194914-867b9e9f-bb6f-4db6-a24a-a9ff69e19e7f.png)

This is the result of the second part:
```
vis_circos(ov)
```


![Image](https://user-images.githubusercontent.com/72346144/180195290-1c490588-7881-46c6-88e3-3f32cedb743f.png)

I believe you have the error due to a version conflict of the library. I recommend you try to update immunarch package:
```
install.packages(c("devtools", "pkgload"))
devtools::install_github("immunomind/immunarch", ref="dev")
devtools::reload(pkgload::inst("immunarch"))
```
Than run your code again.

Please let me know if that helped.

Enjoy your day,
Maria Samokhina

**Comment by dmnoyong** [comment]
Hi Maria,

Thanks for your help.
Yes you're right, updating the package did work.

Best regards,
Damian

**Comment by antoine4ucsd** [comment]
Hello
sorry for bothering. I am trying to plot my data with vis_circos but the output is not a plot but rather a dataframe???
that must be something obvious I am missing here...

```
ov <- repOverlap(immdata$data[immdata$meta$pid==ID1&immdata$meta$location%in%selected_tissues])
> vis(ov, .plot = "circos")
> p1 <-vis(ov, .plot = "circos")
> p1
               rn              cn value1 value2 o1 o2  x1  x2       col
1  ID1_Ileum  ID1_Ileum      0      0  3  6 122 244 #C7C9FD7F
2   ID1_PBMC  ID1_Ileum     82     82  1  5  82 244 #0A8E597F
3 ID1_Rectum  ID1_Ileum     40     40  2  4  58 162 #ABCEEA7F
4  ID1_Ileum   ID1_PBMC     82     82  2  4 122 182 #C7C9FD7F
5   ID1_PBMC   ID1_PBMC      0      0  3  6 100 200 #0A8E597F
6 ID1_Rectum   ID1_PBMC     18     18  1  5  18 200 #ABCEEA7F
7  ID1_Ileum ID1_Rectum     40     40  1  5  40 116 #C7C9FD7F
8   ID1_PBMC ID1_Rectum     18     18  2  4 100  76 #0A8E597F
9 ID1_Rectum ID1_Rectum      0      0  3  6  58 116 #ABCEEA7F
```

thank you in advance!

**Comment by antoine4ucsd** [comment]
sorry - it works after relaunching R...
