### ISSUE TITLE
Alignment on the germline

### ISSUE THREAD

**Issue by NoELJ22** [immunomind/immunarch#299]
## ❓ Questions and Help
Hello, 
I'm a new user of immunarch and I've question about the germline's CDR3 sequence. 
1) Why the germline used for the clones alignment have its CDR3 sequence masked with 'N' ?
2) Is it possible to have the SHM rate with the mutations on the CDR3 region ?

Thank you.

**Comment by Alexander230** [comment]
Hello, @NoELJ22!

I'm Aleksandr Popov, a developer of Immunarch package. Thank you for using our software!

CDR3 region is highly variable, that's why there are reference sequences for V and J genes in the database, and no sequences for CDR3. Germline is built from V and J genes that are detected by preprocessing software (such as MiXCR), and CDR3 region is unknown, so it's filled with N. By the same reason, CDR3 is excluded from SHM calculation.

Best regards,
Aleksandr

**Comment by NoELJ22** [comment]
Hello @Alexander230,

Thank you for your clear answer. So, I have another question.
How is the CDR3 of the Common Ancestor generated in the phylogenetic analysis ? 
And why are there amino acids in its sequence? 

Thank you.

**Comment by Alexander230** [comment]
Phylogenetic analysis uses Phylip software to build the tree and generate intermediate sequences between germline and clonotype sequences in nodes of the tree. Phylip can predict nucleotides in the common ancestors from clonotype sequences, so these predicted nucleotides are used in Immunarch. Distances between tree nodes (DistanceNT and DistanceAA in the table) are calculated by V and J genes (excluding CDR3), but if you need distances with CDR3 when it's available, you can calculate them manually like here https://github.com/immunomind/immunarch/blob/bcr-pipeline-fixes/R/phylip.R#L258, but just use full `seq` and `ancestor` sequences without cutting V and J genes from them.

Best regards,
Aleksandr

**Comment by NoELJ22** [comment]
Ok, I have a better understanding of the pipline. 
Thanks for your help.
