### ISSUE TITLE
repClonalFamily does not generate expected columns

### ISSUE THREAD

**Issue by mknewline** [immunomind/immunarch#332]
Hello and thank you so much for Immunarch!

When I run repClonalFamily it fails to generate some expected columns (referring to this list https://immunarch.com/reference/repClonalFamily.html) . In particular, I miss the following ones:
*  V.germline.nt:
*  J.germline.nt
*  CDR3.germline.length
*  V.length
*  J.length

These columns cannot be generated even using your sample data from data(bcrdata). I have the same results with my own data.

Can you please help me with this?

Many thanks!
Michele

**Comment by Alexander230** [comment]
Hello, Michele!

The instruction on the site is not yet updated, I will put the new version there soon. BCR pipeline in the new version of Immunarch calculates everything from FR and CDR regions, to remove dependency from columns that are missing in some of the input formats. And in the new version, lengths of V, J and CDR3 in a germline and clonotypes from which it was built, are the same. So, you can reconstruct these columns if you need them. Here is an example:

First, prepare repClonalFamily results:

```
data(bcrdata)
clusters <- seqCluster(bcrdata$data, seqDist(bcrdata$data), .fixed_threshold = 3)
cf <- clusters[["full_clones"]] %>% repGermline() %>% repAlignLineage(.min_lineage_sequences = 2) %>% repClonalFamily()
```

Second, unnest the "Sequences" sub-tables, to make the dataframe 1 line per clonotype, rather than 1 line per cluster:

```
clonotypes_df <- cf %>% unnest("Sequences")
```

And then calculate the columns that you need:
```
clonotypes_df %<>% mutate(
    V.length = str_length(FR1.nt) + str_length(CDR1.nt) + str_length(FR2.nt) + str_length(CDR2.nt) + str_length(FR3.nt),
    J.length = str_length(FR4.nt),
    CDR3.germline.length = str_length(CDR3.nt),
    V.germline.nt = substr(Germline.Input, 1, V.length),
    J.germline.nt = substr(Germline.Input, V.length + CDR3.germline.length + 1, str_length(Germline.Input))
)
```

Best regards,
Aleksandr

**Comment by mknewline** [comment]
Thank you Alexander, that's brilliant! Loving Immunarch, thanks for you work.

Michele
