### ISSUE TITLE
Parser for RTCR

### ISSUE THREAD

**Issue by vadimnazarov** [immunomind/immunarch#91]
https://github.com/uubram/RTCR

**Comment by uubram** [comment]
Dear Vadim,

Thank you for your interest in RTCR! As per your request, see below for an example output file. I'm not sure if it's helpful, but RTCR includes a [parser](https://github.com/uubram/RTCR/blob/master/tcR_RTCR_parser.R) for an older version of your software.

[RTCR_output_example.zip](https://github.com/immunomind/immunarch/files/4978152/RTCR_output_example.zip)

Best wishes,
Bram

**Comment by vadimnazarov** [comment]
Thank you, very helpful!

Oh, I know! But we redesigned and will be redesigning the parsers, so having a "gold standard" output file is extremely important here. This is the reason I asked you personally instead of running the software by myself, because I want to make sure we have this "gold standard", as well as a connection in case of any changes such as major version update. Thank you again!

**Comment by uubram** [comment]
Dear Vadim,

As of today, the output of RTCR conforms to the Adaptive Immune Receptor Repertoire (AIRR) Community format. Since immunarch supports the AIRR format, it is already able to parse the output of the latest version (0.5.0) of RTCR. You're of course free to also support the output of older versions of RTCR.

Best wishes,
Bram

**Comment by vadimnazarov** [comment]
Closing this issue for now. The next version of Immunarch will mostly support the AIRR Standard data format.

More details on the next version of Immunarch are here: https://b-t.cr/t/immunarch-will-significantly-evolve-but-it-will-break-things-and-we-need-your-help/1123
