### ISSUE TITLE
Using ggplot2 mappings in `vis` function

### ISSUE THREAD

**Issue by aguang** [immunomind/immunarch#99]
## ❓ Questions and Help

Is there a way to get ggplot2 aesthetic mappings in the `vis` function? For example, if I wanted one column from the metadata table to be color and another to be shape in the MDS plots. In the example below I would like Sex to be the color, and ID to be the shape, but it doesn't seem like I can just put in an `aes` argument as it's not a recognized argument.

Example:
```{r}
data(immdata)
imm_ov1 <- repOverlap(immdata$data, .method = "public", .verbose = F)
repOverlapAnalysis(imm_ov1, "mds") %>% vis(.by=c("Sex","ID"),.meta=immdata$meta)
# does not work
# repOverlapAnalysis(imm_ov1, "mds") %>% vis(.by=c("Sex","ID"),.meta=immdata$meta,aes(color=Sex,shape=ID))
# Error in !.point : invalid argument type
```

**Comment by vadimnazarov** [comment]
Hi @aguang 

Right, it's not supported (yet?) due to the implementation complexities. However, we provided several workarounds.

First, there is `fixVis` that can interactively change your plots: https://immunarch.com/reference/fixVis.html

Second, you can manipulate ggplot object: http://www.cookbook-r.com/Graphs/

Does it work for you?

**Comment by aguang** [comment]
Yes, I know how to manipulate ggplot objects, was just hoping for something easier. Ok, thank you!
